const selectedRegion = 'nm';

// Copyright (c) 2024 Sierra Burkhart
// License: GNU General Public License version 3 (GPLv3)
// See full license text in file "LICENSE" at root of project directory

import { Appearance } from "react-native";

const selectedTheme = Appearance.getColorScheme();

// Attributes for all available regions
const regions = {
	nv: {
		name: "Nevada",
		abbr: "NV",
		nickname: "Silver State",
		developerImageCaption: "Your developer while touring the Historic Fourth Ward School Museum in Virginia City, Storey County.",
		statewideMapExtent: {lat_min: 34.5, lat_max: 42.5, lon_min: -121.0, lon_max: -112.0},
		aboutSplashWidth: 0.912109375,
		light: {
			activeTabBackground: "#005a9c",
			primaryBackground: "#005a9c",
			primaryBackgroundDarker: "#004b83",
			primaryBackgroundDarkest: "#003d69",
			primaryBackgroundLighter: "#0069b6",
			primaryBackgroundLightest: "#0086e9",
			lightOnBackground: "#aed1ea",
			lighterOnBackground: "#d6e8f5",
			contrastOnBackground: "#ffffff",
			contrastOnSplashBackground: "#ffffff",
			splashBackground: "#519fbb",
			listBackground: "#ffffff",
			headerFont: "Rye",
			subheaderFont: "AsapCondensed",
			bodyFont: "EBGaramond",
			bodyHighlight: "#888888",
			bodyHeader: "#666666",
			bodyText: "#444444",
			bodyDark: "#222222",
			highlightedRow: "#dfedf7",
			separatorColor: "#CED0CE",
			modalHeader: "#666666",
			aboutSplashWidth: 0.912109375
		},
		dark: {
			activeTabBackground: "#aed1ea",
			primaryBackground: "#005a9c",
			primaryBackgroundDarker: "#004b83",
			primaryBackgroundDarkest: "#003d69",
			primaryBackgroundLighter: "#0069b6",
			primaryBackgroundLightest: "#0086e9",
			lightOnBackground: "#aed1ea",
			lighterOnBackground: "#d6e8f5",
			contrastOnBackground: "#ffffff",
			contrastOnSplashBackground: "#ffffff",
			splashBackground: "#519fbb",
			listBackground: "#333333",
			headerFont: "Rye",
			subheaderFont: "AsapCondensed",
			bodyFont: "EBGaramond",
			bodyHighlight: "#ababab",
			bodyHeader: "#666666",
			bodyText: "#eeeeee",
			bodyDark: "#efefef",
			highlightedRow: "#666666",
			separatorColor: "#666666",
			modalBackground: "#444444",
			modalHeader: "#aaaaaa",
			aboutSplashWidth: 0.912109375
		}
	},
	"nm": {
		name: "New Mexico",
		abbr: "NM",
		nickname: "Land of Enchantment",
		developerImageCaption: "Your developer in front of the home built by her fourth-great grandfather Samuel B. Watrous near the junction of the Mora River and Sapello River in Watrous (formerly La Junta de los Ríos), Mora County.",
		statewideMapExtent: {lat_min: 34.5, lat_max: 42.5, lon_min: -121.0, lon_max: -112.0},
		aboutSplashWidth: 0.648780487804878,
		light: {
			activeTabBackground: "#9c322f",
			primaryBackground: "#9c322f",
			primaryBackgroundDarker: "#7C2825",
			primaryBackgroundDarkest: "#5D1E1C",
			primaryBackgroundLighter: "#0069b6",
			primaryBackgroundLightest: "#0086e9",
			lightOnBackground: "#fef6d4",
			lighterOnBackground: "#FFFBED",
			contrastOnBackground: "#ffffff",
			contrastOnSplashBackground: "#232622",
			splashBackground: "#b1bfae",
			listBackground: "#ffffff",
			headerFont: "Rye",
			subheaderFont: "AsapCondensed",
			bodyFont: "EBGaramond",
			bodyHighlight: "#888888",
			bodyHeader: "#666666",
			bodyText: "#444444",
			bodyDark: "#222222",
			highlightedRow: "#FFFBED",
			separatorColor: "#CED0CE",
			modalHeader: "#666666",
		},
		dark: {
			activeTabBackground: "#fef6d4",
			primaryBackground: "#9c322f",
			primaryBackgroundDarker: "#7C2825",
			primaryBackgroundDarkest: "#5D1E1C",
			primaryBackgroundLighter: "#0069b6",
			primaryBackgroundLightest: "#0086e9",
			lightOnBackground: "#fef6d4",
			lighterOnBackground: "#FFFBED",
			contrastOnBackground: "#ffffff",
			contrastOnSplashBackground: "#232622",
			splashBackground: "#b1bfae",
			listBackground: "#333333",
			headerFont: "Rye",
			subheaderFont: "AsapCondensed",
			bodyFont: "EBGaramond",
			bodyHighlight: "#ababab",
			bodyHeader: "#666666",
			bodyText: "#eeeeee",
			bodyDark: "#efefef",
			highlightedRow: "#666666",
			separatorColor: "#666666",
			modalBackground: "#444444",
			modalHeader: "#aaaaaa",
		}
	},
	"ca": {
		name: "California",
		abbr: "CA",
		nickname: "Golden State",
		developerImageCaption: "Your developer in her backyard, overlooking the valley of the San Luis Rey river in San Diego County.",
		statewideMapExtent: {lat_min: 34.5, lat_max: 42.5, lon_min: -121.0, lon_max: -112.0},
		light: {
			primaryBackground: "#005a9c",
			primaryBackgroundDarker: "#004b83",
			primaryBackgroundDarkest: "#003d69",
			primaryBackgroundLighter: "#0069b6",
			primaryBackgroundLightest: "#0086e9",
			lightOnBackground: "#aed1ea",
			lighterOnBackground: "#d6e8f5",
			contrastOnBackground: "#ffffff",
			splashBackground: "#519fbb",
			listBackground: "#ffffff",
			headerFont: "Rye",
			subheaderFont: "AsapCondensed",
			bodyFont: "EBGaramond",
			bodyHighlight: "#888888",
			bodyHeader: "#666666",
			bodyText: "#444444",
			bodyDark: "#222222",
			highlightedRow: "#dfedf7",
			separatorColor: "#CED0CE",
			modalHeader: "#666666",
		},
		dark: {
			primaryBackground: "#005a9c",
			primaryBackgroundDarker: "#004b83",
			primaryBackgroundDarkest: "#003d69",
			primaryBackgroundLighter: "#0069b6",
			primaryBackgroundLightest: "#0086e9",
			lightOnBackground: "#aed1ea",
			lighterOnBackground: "#d6e8f5",
			contrastOnBackground: "#ffffff",
			splashBackground: "#519fbb",
			listBackground: "#333333",
			headerFont: "Rye",
			subheaderFont: "AsapCondensed",
			bodyFont: "EBGaramond",
			bodyHighlight: "#ababab",
			bodyHeader: "#666666",
			bodyText: "#eeeeee",
			bodyDark: "#efefef",
			highlightedRow: "#666666",
			separatorColor: "#666666",
			modalBackground: "#444444",
			modalHeader: "#aaaaaa"
		}
	}
}

export const region = regions[selectedRegion];
export const theme = regions[selectedRegion][selectedTheme];