const selectedRegion = 'nm';

// Copyright (c) 2024 Sierra Burkhart
// License: GNU General Public License version 3 (GPLv3)
// See full license text in file "LICENSE" at root of project directory

import { Appearance } from "react-native";

const selectedTheme = Appearance.getColorScheme();

// Attributes for all available regions
const regions = {
	nv: {
		name: "Nevada",
		abbr: "NV",
		nickname: "Silver State",
		statewideMapExtent: {lat_min: 35.003, lat_max: 42.003, lon_min: -120.0037, lon_max: -114.0436},
		aboutSplashWidth: 0.912109375,
		light: {
			activeTabBackground: "#005a9c",
			primaryBackground: "#005a9c",
			primaryBackgroundDarker: "#004b83",
			primaryBackgroundDarkest: "#003d69",
			primaryBackgroundLighter: "#0069b6",
			primaryBackgroundLightest: "#0086e9",
			lightOnBackground: "#aed1ea",
			lighterOnBackground: "#d6e8f5",
			contrastOnBackground: "#d6e8f5",
			contrastOnSplashBackground: "#ffffff",
			splashBackground: "#519fbb",
			listBackground: "#ffffff",
			headerFont: "Rye",
			subheaderFont: "AsapCondensed",
			bodyFont: "EBGaramond",
			bodyHighlight: "#888888",
			bodyHeader: "#666666",
			bodyText: "#444444",
			bodyDark: "#222222",
			highlightedRow: "#dfedf7",
			separatorColor: "#CED0CE",
			modalHeader: "#666666",
		},
		dark: {
			activeTabBackground: "#aed1ea",
			primaryBackground: "#005a9c",
			primaryBackgroundDarker: "#004b83",
			primaryBackgroundDarkest: "#003d69",
			primaryBackgroundLighter: "#0069b6",
			primaryBackgroundLightest: "#0086e9",
			lightOnBackground: "#aed1ea",
			lighterOnBackground: "#d6e8f5",
			contrastOnBackground: "#d6e8f5",
			contrastOnSplashBackground: "#ffffff",
			splashBackground: "#519fbb",
			listBackground: "#333333",
			headerFont: "Rye",
			subheaderFont: "AsapCondensed",
			bodyFont: "EBGaramond",
			bodyHighlight: "#ababab",
			bodyHeader: "#666666",
			bodyText: "#eeeeee",
			bodyDark: "#efefef",
			highlightedRow: "#666666",
			separatorColor: "#666666",
			modalBackground: "#444444",
			modalHeader: "#aaaaaa",
		}
	},
	nm: {
		name: "New Mexico",
		abbr: "NM",
		nickname: "Land of Enchantment",
		statewideMapExtent: {lat_min: 31.3337, lat_max: 36.9982, lon_min: -109.0489, lon_max: -103.0023},
		aboutSplashWidth: 0.648780487804878,
		light: {
			activeTabBackground: "#3891a4",
			primaryBackground: "#06768d",
			primaryBackgroundDarker: "#055e71",
			primaryBackgroundDarkest: "#033b47",
			primaryBackgroundLighter: "#3891a4",
			primaryBackgroundLightest: "#83bbc6",
			lightOnBackground: "#C9E1E6",
			lighterOnBackground: "#E0EDF0",
			contrastOnBackground: "#E0EDF0",
			contrastOnSplashBackground: "#232622",
			splashBackground: "#b1bfae",
			listBackground: "#ffffff",
			headerFont: "Rye",
			subheaderFont: "AsapCondensed",
			bodyFont: "EBGaramond",
			bodyHighlight: "#888888",
			bodyHeader: "#666666",
			bodyText: "#444444",
			bodyDark: "#222222",
			highlightedRow: "#E0EDF0",
			separatorColor: "#CED0CE",
			modalHeader: "#666666",
		},
		dark: {
			activeTabBackground: "#C9E1E6",
			primaryBackground: "#06768d",
			primaryBackgroundDarker: "#055e71",
			primaryBackgroundDarkest: "#033b47",
			primaryBackgroundLighter: "#3891a4",
			primaryBackgroundLightest: "#83bbc6",
			lightOnBackground: "#C9E1E6",
			lighterOnBackground: "#E0EDF0",
			contrastOnBackground: "#E0EDF0",
			contrastOnSplashBackground: "#232622",
			splashBackground: "#b1bfae",
			listBackground: "#333333",
			headerFont: "Rye",
			subheaderFont: "AsapCondensed",
			bodyFont: "EBGaramond",
			bodyHighlight: "#ababab",
			bodyHeader: "#666666",
			bodyText: "#eeeeee",
			bodyDark: "#efefef",
			highlightedRow: "#666666",
			separatorColor: "#666666",
			modalBackground: "#444444",
			modalHeader: "#aaaaaa",
		}
	},
	ca: {
		name: "California",
		abbr: "CA",
		nickname: "Golden State",
		statewideMapExtent: {lat_min: 32.5121, lat_max: 42.0126, lon_min: -124.6509, lon_max: -114.1315},
		light: {
			primaryBackground: "#005a9c",
			primaryBackgroundDarker: "#004b83",
			primaryBackgroundDarkest: "#003d69",
			primaryBackgroundLighter: "#0069b6",
			primaryBackgroundLightest: "#0086e9",
			lightOnBackground: "#aed1ea",
			lighterOnBackground: "#d6e8f5",
			contrastOnBackground: "#ffffff",
			splashBackground: "#519fbb",
			listBackground: "#ffffff",
			headerFont: "Rye",
			subheaderFont: "AsapCondensed",
			bodyFont: "EBGaramond",
			bodyHighlight: "#888888",
			bodyHeader: "#666666",
			bodyText: "#444444",
			bodyDark: "#222222",
			highlightedRow: "#dfedf7",
			separatorColor: "#CED0CE",
			modalHeader: "#666666",
		},
		dark: {
			primaryBackground: "#005a9c",
			primaryBackgroundDarker: "#004b83",
			primaryBackgroundDarkest: "#003d69",
			primaryBackgroundLighter: "#0069b6",
			primaryBackgroundLightest: "#0086e9",
			lightOnBackground: "#aed1ea",
			lighterOnBackground: "#d6e8f5",
			contrastOnBackground: "#ffffff",
			splashBackground: "#519fbb",
			listBackground: "#333333",
			headerFont: "Rye",
			subheaderFont: "AsapCondensed",
			bodyFont: "EBGaramond",
			bodyHighlight: "#ababab",
			bodyHeader: "#666666",
			bodyText: "#eeeeee",
			bodyDark: "#efefef",
			highlightedRow: "#666666",
			separatorColor: "#666666",
			modalBackground: "#444444",
			modalHeader: "#aaaaaa"
		}
	},
	co: {
		name: "Colorado",
		abbr: "CO",
		nickname: "Centennial State",
		statewideMapExtent: {lat_min: 36.9949, lat_max: 41.0006, lon_min: -109.0489, lon_max: -102.0424},
		aboutSplashWidth: 0.68344465648855,
		light: {
			activeTabBackground: "#005a9c",
			primaryBackground: "#005a9c",
			primaryBackgroundDarker: "#004b83",
			primaryBackgroundDarkest: "#003d69",
			primaryBackgroundLighter: "#0069b6",
			primaryBackgroundLightest: "#0086e9",
			lightOnBackground: "#aed1ea",
			lighterOnBackground: "#d6e8f5",
			contrastOnBackground: "#d6e8f5",
			contrastOnSplashBackground: "#444444",
			splashBackground: "#fff4dc",
			listBackground: "#ffffff",
			headerFont: "Rye",
			subheaderFont: "AsapCondensed",
			bodyFont: "EBGaramond",
			bodyHighlight: "#888888",
			bodyHeader: "#666666",
			bodyText: "#444444",
			bodyDark: "#222222",
			highlightedRow: "#dfedf7",
			separatorColor: "#CED0CE",
			modalHeader: "#666666",
		},
		dark: {
			activeTabBackground: "#aed1ea",
			primaryBackground: "#005a9c",
			primaryBackgroundDarker: "#004b83",
			primaryBackgroundDarkest: "#003d69",
			primaryBackgroundLighter: "#0069b6",
			primaryBackgroundLightest: "#0086e9",
			lightOnBackground: "#aed1ea",
			lighterOnBackground: "#d6e8f5",
			contrastOnBackground: "#d6e8f5",
			contrastOnSplashBackground: "#fff4dc",
			splashBackground: "#514d46",
			listBackground: "#333333",
			headerFont: "Rye",
			subheaderFont: "AsapCondensed",
			bodyFont: "EBGaramond",
			bodyHighlight: "#ababab",
			bodyHeader: "#666666",
			bodyText: "#eeeeee",
			bodyDark: "#efefef",
			highlightedRow: "#666666",
			separatorColor: "#666666",
			modalBackground: "#444444",
			modalHeader: "#aaaaaa",
		}
	},
	az: {
		name: "Arizona",
		abbr: "AZ",
		nickname: "Grand Canyon State",
		statewideMapExtent: {lat_min: 31.3325, lat_max: 37.0004, lon_min: -114.8126, lon_max: -109.0475},
		aboutSplashWidth: 0.757395038167939,
		light: {
			activeTabBackground: "#9c322f",
			primaryBackground: "#9c322f",
			primaryBackgroundDarker: "#7C2825",
			primaryBackgroundDarkest: "#5D1E1C",
			primaryBackgroundLighter: "#0069b6",
			primaryBackgroundLightest: "#0086e9",
			lightOnBackground: "#fef6d4",
			lighterOnBackground: "#FFFBED",
			contrastOnBackground: "#FFFBED",
			contrastOnSplashBackground: "#232622",
			splashBackground: "#c9b9af",
			listBackground: "#ffffff",
			headerFont: "Rye",
			subheaderFont: "AsapCondensed",
			bodyFont: "EBGaramond",
			bodyHighlight: "#888888",
			bodyHeader: "#666666",
			bodyText: "#444444",
			bodyDark: "#222222",
			highlightedRow: "#FFFBED",
			separatorColor: "#CED0CE",
			modalHeader: "#666666",
		},
		dark: {
			activeTabBackground: "#fef6d4",
			primaryBackground: "#9c322f",
			primaryBackgroundDarker: "#7C2825",
			primaryBackgroundDarkest: "#5D1E1C",
			primaryBackgroundLighter: "#0069b6",
			primaryBackgroundLightest: "#0086e9",
			lightOnBackground: "#fef6d4",
			lighterOnBackground: "#FFFBED",
			contrastOnBackground: "#FFFBED",
			contrastOnSplashBackground: "#232622",
			splashBackground: "#c9b9af",
			listBackground: "#333333",
			headerFont: "Rye",
			subheaderFont: "AsapCondensed",
			bodyFont: "EBGaramond",
			bodyHighlight: "#ababab",
			bodyHeader: "#666666",
			bodyText: "#eeeeee",
			bodyDark: "#efefef",
			highlightedRow: "#666666",
			separatorColor: "#666666",
			modalBackground: "#444444",
			modalHeader: "#aaaaaa",
		}
	},
	mt: {
		name: "Montana",
		abbr: "MT",
		nickname: "Treasure State",
		statewideMapExtent: {lat_min: 44.3563, lat_max: 48.9991, lon_min: -116.0458, lon_max: -104.0186},
		aboutSplashWidth: 0.912109375,
		light: {
			activeTabBackground: "#005a9c",
			primaryBackground: "#005a9c",
			primaryBackgroundDarker: "#004b83",
			primaryBackgroundDarkest: "#003d69",
			primaryBackgroundLighter: "#0069b6",
			primaryBackgroundLightest: "#0086e9",
			lightOnBackground: "#aed1ea",
			lighterOnBackground: "#d6e8f5",
			contrastOnBackground: "#d6e8f5",
			contrastOnSplashBackground: "#ffffff",
			splashBackground: "#519fbb",
			listBackground: "#ffffff",
			headerFont: "Rye",
			subheaderFont: "AsapCondensed",
			bodyFont: "EBGaramond",
			bodyHighlight: "#888888",
			bodyHeader: "#666666",
			bodyText: "#444444",
			bodyDark: "#222222",
			highlightedRow: "#dfedf7",
			separatorColor: "#CED0CE",
			modalHeader: "#666666",
		},
		dark: {
			activeTabBackground: "#aed1ea",
			primaryBackground: "#005a9c",
			primaryBackgroundDarker: "#004b83",
			primaryBackgroundDarkest: "#003d69",
			primaryBackgroundLighter: "#0069b6",
			primaryBackgroundLightest: "#0086e9",
			lightOnBackground: "#aed1ea",
			lighterOnBackground: "#d6e8f5",
			contrastOnBackground: "#d6e8f5",
			contrastOnSplashBackground: "#ffffff",
			splashBackground: "#519fbb",
			listBackground: "#333333",
			headerFont: "Rye",
			subheaderFont: "AsapCondensed",
			bodyFont: "EBGaramond",
			bodyHighlight: "#ababab",
			bodyHeader: "#666666",
			bodyText: "#eeeeee",
			bodyDark: "#efefef",
			highlightedRow: "#666666",
			separatorColor: "#666666",
			modalBackground: "#444444",
			modalHeader: "#aaaaaa",
		}
	},
}

export const region = regions[selectedRegion];
export const theme = regions[selectedRegion][selectedTheme];